# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Day 1 Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-using-dotnet:
   uses: ryewilson/aoc-2022/.github/workflows/dotnet.yml@main
   with:
     project-path: ./day1/csharp
